# - name: task_name
#   condition_images: vision condition images path
#   video_path: str, default null, used for video2video 
#   prompt: text to guide image generation
#   ipadapter_image: image_path for IP-Apdater
#   refer_image: image_path for referencenet, generally speaking, same as ipadapter_image
#   height: int # The shorter the image size, the larger the motion amplitude, and the lower video quality.
#   width: int #  The longer the W&H, the smaller the motion amplitude, and the higher video quality.
#   img_length_ratio: float, generation video size is (height, width) * img_length_ratio

# text/image2video
- condition_images: ./data/images/girl_play_guitar2.jpeg
  eye_blinks_factor: 1.8
  height: 1002
  img_length_ratio: 1.248
  ipadapter_image: ${.condition_images}
  name: girl_play_guitar2
  prompt: (masterpiece, best quality, highres:1), playing guitar
  refer_image: ${.condition_images}
  video_path: null
  width: 564
  
